---
title: "Chapter 07: Group Comparisons"
---

<!-- Lecture a -->

## [07a] t-tests / Effect Sizes / Paired Groups

### Topics
- NHST Approaches
- Effect Sizes

### Files
- [socialproblems.csv](../../data/socialproblems.csv){download="socialproblems.csv"}
- [teaching_ratings.csv](../../data/teaching_ratings.csv){download="teaching_ratings.csv"}

### Readings
- [View on Canvas](https://canvas.ku.edu/courses/{{< meta canvas-id >}}/files/folder/Unit%20B){target="_blank"}

### Slides

```{=html}
<iframe class="slide-deck" src="a_Slides.html" title="[07a] Slideshow">
</iframe>
```

::: {.fs80}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

<!-- Lecture b -->

## [07b] One-way ANOVA / Effect Sizes / Contrasts

### Topics
- One-way ANOVA in R
- Post-hoc Tests

### Files
- [salaries.csv](../../data/salaries.csv){download="salaries.csv"}

### Readings
- [View on Canvas](https://canvas.ku.edu/courses/{{< meta canvas-id >}}/files/folder/Unit%20B){target="_blank"}

### Slides

```{=html}
<iframe class="slide-deck" src="b_Slides.html" title="[07b] Slideshow">
</iframe>
```

::: {.fs80}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

<!-- Assignment -->

## Assignment

- [Chapter 07 Assignment](assignment.qmd)

<!-- Bottom Nav -->

```{=html}
<div style="display: flex; justify-content: space-between; margin-top: 3rem;">
  <a href="../06/index.html" class="btn btn-outline-primary" role="button">&laquo;&nbsp;&nbsp;Chapter 06</a>

  <a href="../08/index.html" class="btn btn-primary" role="button">Chapter 08&nbsp;&nbsp;&raquo;</a>
</div>
```
