---
title: "Moderation"
subtitle: "Unit {{< meta unit >}} · Chapter {{< meta chapter >}}"
pagetitle: "Chapter {{< meta chapter >}}: Moderation"
---

<!-- Lecture a -->

## [08a] Continuous Moderation

::: {.topics}
- Continuous-by-Continuous
- Interaction Patterns
- Centering with Interactions
:::

### Files {.res-files}
- [exercise.csv](../../data/exercise.csv){download="exercise.csv"}

### Readings {.res-readings}
- *Applied Multiple Regression/Correlation Analysis*, §7.1--7.5, 7.7
- [Interactions in R](https://stats.idre.ucla.edu/r/seminars/interactions-r/), *UCLA OARC*
- Finsaas \& Goldstein (2021), [Do Simple Slopes Follow-Up Tests Lead Us Astray? Advancements in the Visualization and Reporting of Interactions](https://doi.org/10/ggsng9), *Psychological Methods*
- Rohrer \& Arslan (2021), [Precise Answers to Vague Questions: Issues With Interactions](https://doi.org/10/gk9zkd), *AMPPS*

### Slides

```{=html}
<iframe class="slide-deck" src="a_Slides.html" title="[08a] Slideshow">
</iframe>
```

::: {.fs80}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

### Activity {.res-activity}
- [Lecture 08a Activity](a_activity.qmd)

### Assignment {.res-assignment}
- [Lecture 08a Assignment](a_assignment.qmd)

<!-- Lecture b -->

<!-- Lecture b -->

## [08b] Categorical Moderation

::: {.topics}
- Binary-by-Continuous
- Nominal-by-Continuous
- Categorical-by-Categorical
- Three-Way Interactions
:::

### Files {.res-files}
- [exercise.csv](../../data/exercise.csv){download="exercise.csv"}

### Readings {.res-readings}
- *Applied Multiple Regression/Correlation Analysis*, §7.6, 7.8, 9.1--9.3
- [Interactions in R](https://stats.idre.ucla.edu/r/seminars/interactions-r/), *UCLA OARC*

### Slides

```{=html}
<iframe class="slide-deck" src="b_Slides.html" title="[08b] Slideshow">
</iframe>
```

::: {.fs80}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

### Activity {.res-activity}
- [Lecture 08b Activity](b_activity.qmd)

### Assignment {.res-assignment}
- [Lecture 08b Assignment](b_assignment.qmd)

<!-- Bottom Nav -->

```{=html}
<div style="display: flex; justify-content: space-between; margin-top: 3rem;">
  <a href="../../C/07/index.html" class="btn btn-outline-primary" role="button">&laquo;&nbsp;&nbsp;Chapter 07</a>
  <a href="../../C/09/index.html" class="btn btn-primary" role="button">Chapter 09&nbsp;&nbsp;&raquo;</a>
</div>
```
