---
title: "Chapter 05: Hypothesis Testing"
---

<!-- Lecture a -->

## [05a] NHST & p-values

::: {.topics}
- Statistical Hypotheses
- NHST Logic
- NHST Nuts and Bolts
- $p$-values and  Pragmatics
:::

### Readings {.res-readings}
- [Hypothesis Testing, §11.1--11.7](https://learningstatisticswithr.com/11-hypothesistesting.html) --- *Learning Statistics with R*
- [Comparing Two Means, §13.1--13.2](https://learningstatisticswithr.com/13-ttest.html) --- *Learning Statistics with R*
- Cassidy et al. (2019), [Failing Grade: 89% of Introduction-to-Psychology Textbooks That Define or Explain Statistical Significance Do So Incorrectly](https://doi.org/10.1177/2515245919858072) --- *AMPPS*

### Slides

```{=html}
<iframe class="slide-deck" src="a_Slides.html" title="[05a] Slideshow">
</iframe>
```

::: {.fs80}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

### Assignment {.res-assignment}
- [Lecture 05a Assignment](a_assignment.qmd)

<!-- Lecture b -->

<!-- Lecture b -->

## [05b] Correlation & Inference

::: {.topics}
- Calculating  Correlations
- Statistical Inference
:::

### Files {.res-files}
- [cigarettes.csv](../../data/cigarettes.csv){download="cigarettes.csv"}

### Readings {.res-readings}
- [Descriptive Statistics](https://learningstatisticswithr.com/05-descriptives.html) --- *Learning Statistics with R*
- *Beyond Significance Testing*, pp. 126--128, 138--140

### Slides

```{=html}
<iframe class="slide-deck" src="b_Slides.html" title="[05b] Slideshow">
</iframe>
```

::: {.fs80}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

### Assignment {.res-assignment}
- [Lecture 05b Assignment](b_assignment.qmd)

<!-- Bottom Nav -->

```{=html}
<div style="display: flex; justify-content: space-between; margin-top: 3rem;">
  <a href="../../B/04/index.html" class="btn btn-outline-primary" role="button">&laquo;&nbsp;&nbsp;Chapter 04</a>
  <a href="../../B/06/index.html" class="btn btn-primary" role="button">Chapter 06&nbsp;&nbsp;&raquo;</a>
</div>
```
