---
title: "Chapter 13: Reporting and Reviewing"
---

<!-- Lecture a -->

## [13a] Reporting & Reviewing

### Readings
- "Research Design" --- *Reviewer's Guide to Quantitative Methods in the Social Sciences*
- "Multiple Regression" --- *Reviewer's Guide to Quantitative Methods in the Social Sciences*

### Slides

```{=html}
<iframe class="slide-deck" src="a_Slides.html" title="[13a] Slideshow">
</iframe>
```

::: {.fs80}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

### Assignment
- [Lecture 13a Assignment](a_assignment.qmd)

<!-- Lecture b -->

<!-- Lecture b -->

## [13b] Translation Activity

### Topics
- Examples
- Activity

### Slides

```{=html}
<iframe class="slide-deck" src="b_Slides.html" title="[13b] Slideshow">
</iframe>
```

::: {.fs80}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

### Assignment
- [Lecture 13b Assignment](b_assignment.qmd)

<!-- Bottom Nav -->

```{=html}
<div style="display: flex; justify-content: space-between; margin-top: 3rem;">
  <a href="../../D/12/index.html" class="btn btn-outline-primary" role="button">&laquo;&nbsp;&nbsp;Chapter 12</a>

</div>
```
