---
title: "Chapter 16: Reporting and Reviewing"
---

<!-- Lecture a -->

## [16a] Reporting & Reviewing

### Readings
- [View on Canvas](https://canvas.ku.edu/courses/{{< meta canvas-id >}}/files/folder/Unit%20D){target="_blank"}

### Slides

```{=html}
<iframe class="slide-deck" src="a_Slides.html" title="[16a] Slideshow">
</iframe>
```

::: {.fs80}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

<!-- Lecture b -->

## [16b] Translation Activity

### Topics
- Examples
- Activity

### Readings
- [View on Canvas](https://canvas.ku.edu/courses/{{< meta canvas-id >}}/files/folder/Unit%20D){target="_blank"}

### Slides

```{=html}
<iframe class="slide-deck" src="b_Slides.html" title="[16b] Slideshow">
</iframe>
```

::: {.fs80}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

<!-- Assignment -->

## Assignment

- [Chapter 16 Assignment](assignment.qmd)

<!-- Bottom Nav -->

```{=html}
<div style="display: flex; justify-content: space-between; margin-top: 3rem;">
  <a href="../15/index.html" class="btn btn-outline-primary" role="button">&laquo;&nbsp;&nbsp;Chapter 15</a>
</div>
```
