---
title: "Chapter 04: Sampling & Estimation"
---

<!-- Lecture a -->

## [04a] Populations & Samples

::: {.topics}
- Research Methods
- Populations and Parameters
- Samples and Statistics
- Estimation and Uncertainty
:::

### Files
- [sleep.csv](../../data/sleep.csv){download="sleep.csv"}

### Readings
- [Estimating Unknown Quantities, §10.1--10.2](https://learningstatisticswithr.com/10-estimation.html) --- *Learning Statistics with R*

### Slides

```{=html}
<iframe class="slide-deck" src="a_Slides.html" title="[04a] Slideshow">
</iframe>
```

::: {.fs80}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

### Assignment
- [Lecture 04a Assignment](a_assignment.qmd)

<!-- Lecture b -->

<!-- Lecture b -->

## [04b] Confidence Intervals

::: {.topics}
- Types of Estimates
- The Normal Distribution
- Central Limit Theorem
- Confidence Intervals
- Practical Matters
:::

### Files
- [sleep.csv](../../data/sleep.csv){download="sleep.csv"}
- [teaching_ratings.csv](../../data/teaching_ratings.csv){download="teaching_ratings.csv"}

### Readings
- [Introduction to Probability, §9.1--9.2, 9.5](https://learningstatisticswithr.com/09-probability.html) --- *Learning Statistics with R*
- [Estimating Unknown Quantities, §10.3--10.6](https://learningstatisticswithr.com/10-estimation.html) --- *Learning Statistics with R*

### Slides

```{=html}
<iframe class="slide-deck" src="b_Slides.html" title="[04b] Slideshow">
</iframe>
```

::: {.fs80}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

### Assignment
- [Lecture 04b Assignment](b_assignment.qmd)

<!-- Bottom Nav -->

```{=html}
<div style="display: flex; justify-content: space-between; margin-top: 3rem;">
  <a href="../../A/03/index.html" class="btn btn-outline-primary" role="button">&laquo;&nbsp;&nbsp;Chapter 03</a>
  <a href="../../B/05/index.html" class="btn btn-primary" role="button">Chapter 05&nbsp;&nbsp;&raquo;</a>
</div>
```
