---
title: "Chapter 02: Projects & Programming"
---

<!-- Lecture a -->

## [02a] Reproducible Workflows

::: {.topics}
- Projects
- Quarto
- Markdown
:::

### Readings {.res-readings}
- [Workflow: Projects](https://r4ds.hadley.nz/workflow-scripts#projects), *R for Data Science*
- [Quarto](https://r4ds.hadley.nz/quarto), *R for Data Science*
- [Getting Started with Quarto](https://quarto.org/docs/get-started/hello/rstudio.html), *Quarto*
- [Quarto Cheat Sheet](https://rstudio.github.io/cheatsheets/html/quarto.html), *Posit*

### Slides

```{=html}
<iframe class="slide-deck" src="a_Slides.html" title="[02a] Slideshow">
</iframe>
```

::: {.fs80}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

### Practice {.res-practice}
- [Lecture 02a Practice](a_practice.qmd)

### Assignment {.res-assignment}
- [Lecture 02a Assignment](a_assignment.qmd)

<!-- Lecture b -->

<!-- Lecture b -->

## [02b] Writing R Code

::: {.topics}
- Assignment
- Naming
- Functions
- Vectors
:::

### Readings {.res-readings}
- [Workflow: Basics](https://r4ds.hadley.nz/workflow-basics), *R for Data Science*
- [Functions](https://r4ds.hadley.nz/functions), *R for Data Science*
- [Vectors](https://adv-r.hadley.nz/vectors-chap.html), *Advanced R*

### Slides

```{=html}
<iframe class="slide-deck" src="b_Slides.html" title="[02b] Slideshow">
</iframe>
```

::: {.fs80}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

### Practice {.res-practice}
- [Lecture 02b Practice](b_practice.qmd)

### Assignment {.res-assignment}
- [Lecture 02b Assignment](b_assignment.qmd)

<!-- Bottom Nav -->

```{=html}
<div style="display: flex; justify-content: space-between; margin-top: 3rem;">
  <a href="../../A/01/index.html" class="btn btn-outline-primary" role="button">&laquo;&nbsp;&nbsp;Chapter 01</a>
  <a href="../../A/03/index.html" class="btn btn-primary" role="button">Chapter 03&nbsp;&nbsp;&raquo;</a>
</div>
```
