---
title: "Chapter 04: Unit A Project"
---

<!-- Lecture a -->

## [04a] Unit A Project

In-class project work

<!-- Lecture b -->

## [04b] Unit A Project

In-class project work

<!-- Project -->

## Project Description

Instead of attending lectures, you will work on a project that puts the Unit A skills to use.
Whereas the assignments in this course use curated datasets that are pre-cleaned and
ready-to-analyze, data in the real world is often a bit messy and needs to be tidied. Projects
are opportunities to work with real-world data that you care about (e.g., data from your own
research lab or domains of interest).

The goal of the Unit A Project is to **prepare a dataset that you select for analysis**. That
may mean reorganizing it a bit to meet the tidy data principles, importing/reading it into R,
and doing some data description and exploration. You should create a Quarto document that
conducts these steps (except perhaps the first, which you may do outside of R), prints the
output, and describes your findings in text.

### Your dataset

- At least **20 rows** and at least **4 columns**
- Some datasets include hundreds of columns and that can be overwhelming, so I recommend
  selecting a subset of the most important/interesting columns to focus on for this project
- Ideally there would be a mix of categorical and continuous variables (but this is not
  required)

### Your description and exploration

- Touch upon at least **4 columns**
- Include at least **2 figures**
- Include some text that describes some take-away points (e.g., the most common values of this
  variable were between these two values, or there seems to be a positive relationship between
  these two variables)

### Grading

| | |
|---|---|
| 1 point | Was your Quarto document set up properly and is it well organized? |
| 1 point | Is your dataset tidy and larger than the minimum requirements? |
| 1 point | Did you import/read in the dataset properly? |
| 1 point | Did you conduct the data exploration properly? |
| 1 point | Did you add some appropriate descriptive/interpretive text? |

<!-- Bottom Nav -->

```{=html}
<div style="display: flex; justify-content: space-between; margin-top: 3rem;">
  <a href="../03/index.html" class="btn btn-outline-primary" role="button">&laquo;&nbsp;&nbsp;Chapter 03</a>

  <a href="../../B/05/index.html" class="btn btn-primary" role="button">Chapter 05&nbsp;&nbsp;&raquo;</a>
</div>
```
