---
title: "Chapter 09: Assumptions, Diagnostics, and Nonlinearity"
---

<!-- Lecture a -->

## [09a] Assumptions and Diagnostics I

### Topics
- Correct Form
- Perfect Predictors
- No Collinearity

### Readings
- *Applied Multiple Regression/Correlation Analysis*, §4.1, 4.3--4.5, 10.5--10.6
- [Collinearity Isn't a Disease That Needs Curing](https://janhove.github.io/analysis/2019/09/11/collinearity) --- *Jan Vanhove*

### Slides

```{=html}
<iframe class="slide-deck" src="a_Slides.html" title="[09a] Slideshow">
</iframe>
```

::: {.fs80}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

### Assignment
- [Lecture 09a Assignment](a_assignment.qmd)

<!-- Lecture b -->

<!-- Lecture b -->

## [09b] Assumptions and Diagnostics II

### Topics
- Constant Error Variance
- Normal Residuals
- Independent Residuals
- Outliers

### Files
- [auto.csv](../../data/auto.csv){download="auto.csv"}
- [yearspubs.csv](../../data/yearspubs.csv){download="yearspubs.csv"}

### Readings
- *Applied Multiple Regression/Correlation Analysis*, §4.1, 4.3--4.5, 10.2--10.4
- Pek, Wong, \& Wong (2018), [How to Address Non-normality: A Taxonomy of Approaches, Reviewed, and Illustrated](https://doi.org/10/gf9r69) --- *Frontiers in Psychology*
- Leys et al. (2019), [How to Classify, Detect, and Manage Univariate and Multivariate Outliers, With Emphasis on Pre-Registration](https://doi.org/10/ghkz2s) --- *IRSP*

### Slides

```{=html}
<iframe class="slide-deck" src="b_Slides.html" title="[09b] Slideshow">
</iframe>
```

::: {.fs80}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

### Assignment
- [Lecture 09b Assignment](b_assignment.qmd)

<!-- Lecture c -->

## [09c] Polynomial Regression

### Topics
- Polynomial Regression
- Quadratic Regression
- Adding Predictors
- Closing Thoughts

### Files
- [salaries.csv](../../data/salaries.csv){download="salaries.csv"}

### Readings
- *Applied Multiple Regression/Correlation Analysis*, §6.1--6.2

### Slides

```{=html}
<iframe class="slide-deck" src="c_Slides.html" title="[09c] Slideshow">
</iframe>
```

::: {.fs80}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

### Assignment
- [Lecture 09c Assignment](c_assignment.qmd)

<!-- Bottom Nav -->

```{=html}
<div style="display: flex; justify-content: space-between; margin-top: 3rem;">
  <a href="../../C/08/index.html" class="btn btn-outline-primary" role="button">&laquo;&nbsp;&nbsp;Chapter 08</a>
  <a href="../../C/10/index.html" class="btn btn-primary" role="button">Chapter 10&nbsp;&nbsp;&raquo;</a>
</div>
```
