---
title: "Chapter 03: Data & Exploration"
---

<!-- Lecture a -->

## [03a] Data Types & Packages

::: {.topics}
- Strings
- Factors
- Packages
:::

### Readings {.res-readings}
- [Strings](https://r4ds.hadley.nz/strings) --- *R for Data Science*
- [Factors](https://r4ds.hadley.nz/factors) --- *R for Data Science*
- [Prerequisites](https://r4ds.hadley.nz/intro#prerequisites) --- *R for Data Science*

### Slides

```{=html}
<iframe class="slide-deck" src="a_Slides.html" title="[03a] Slideshow">
</iframe>
```

::: {.fs80}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

### Practice {.res-practice}
- [Lecture 03a Practice](a_practice.qmd)

### Assignment {.res-assignment}
- [Lecture 03a Assignment](a_assignment.qmd)

<!-- Lecture b -->

<!-- Lecture b -->

## [03b] Importing & Exploring

::: {.topics}
- Data Frames
- Data Files
- Data Exploration
:::

### Files {.res-files}
- [penguins.csv](../../data/penguins.csv){download="penguins.csv"}
- [penguins0.csv](../../data/penguins0.csv){download="penguins0.csv"}
- [gradebook.csv](../../data/gradebook.csv){download="gradebook.csv"}

### Readings {.res-readings}
- [Tidy Data](https://tidyr.tidyverse.org/articles/tidy-data.html) --- *tidyr*
- [Data Import](https://r4ds.hadley.nz/data-import) --- *R for Data Science*
- [Data Transformation](https://r4ds.hadley.nz/data-transform) --- *R for Data Science*
- [Data Visualization](https://r4ds.hadley.nz/data-visualize) --- *R for Data Science*
- [ggplot2: Elegant Graphics for Data Analysis](https://ggplot2-book.org/) --- *Wickham et al.*

### Slides

```{=html}
<iframe class="slide-deck" src="b_Slides.html" title="[03b] Slideshow">
</iframe>
```

::: {.fs80}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

### Practice {.res-practice}
- [Lecture 03b Practice](b_practice.qmd)

### Assignment {.res-assignment}
- [Lecture 03b Assignment](b_assignment.qmd)

<!-- Bottom Nav -->

```{=html}
<div style="display: flex; justify-content: space-between; margin-top: 3rem;">
  <a href="../../A/02/index.html" class="btn btn-outline-primary" role="button">&laquo;&nbsp;&nbsp;Chapter 02</a>
  <a href="../../B/04/index.html" class="btn btn-primary" role="button">Chapter 04&nbsp;&nbsp;&raquo;</a>
</div>
```
